# ===================================================
# CONFIGURATION STREET WORKOUT API
# ===================================================

# Application
spring.application.name=StreetWorkout API
server.port=8080

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/streetworkout?characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=Btsinfo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=VotreCleSuperSecreteDeMinimum256BitsIciPourJWTStreetWorkoutApplicationSecure2024
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:4200,http://localhost:3000

# Logging
logging.level.com.streetworkout=DEBUG
logging.level.org.springframework.security=DEBUG
